# Generated by Django 4.2 on 2023-04-07 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='apartment_area_gte',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='apartment_area_lte',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='price_gte',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='price_lte',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='favorites',
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='favorites',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_users', to='profiles.favorites'),
        ),
    ]
