# Generated by Django 4.2 on 2023-04-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_favorites_apartment_area_gte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
