# Generated by Django 4.2 on 2023-04-07 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_serviceuser_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='favorites',
        ),
        migrations.AddField(
            model_name='favorites',
            name='service_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
