# Generated by Django 4.2 on 2023-04-07 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/')),
                ('city', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('apartment_area', models.FloatField(max_length=30)),
                ('price', models.FloatField(max_length=30)),
                ('published', models.DateTimeField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
