# Generated by Django 4.2 on 2023-04-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentinfo',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
